dist: trusty
group: beta

language: node_js
node_js:
- node
addons:
  firefox: latest-esr
cache:
  directories:
  - node_modules
  - "$HOME/.cache/bower"
before_install:
- "if [ -d node_modules ] && [ x$(cat node_modules/.last-node-version 2>/dev/null) != x$(node -e 'console.log(process.version)') ]; then npm rebuild --update-binary && node -e 'console.log(process.version)' > node_modules/.last-node-version; fi"
before_script:
- npm install web-component-tester bower@1.7.9 polylint
- $(npm bin)/bower install
- $(npm bin)/polylint --no-recursion
script:
- xvfb-run $(npm bin)/wct
